# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1



jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  build-and-test:
      docker:
        - image: cimg/node:16.14.0
      steps:
        - checkout
        - restore_cache:
            key: v1-deps-{{ checksum "package-lock.json" }}
        - run:
            name: Install deps
            command: npm install
        - save_cache:
            key: v1-deps-{{ checksum "package-lock.json" }}
            paths: 
                - node_modules
        - run:
            name: Run tests
            command: npm run test-ci
        - run:
            name: Copy tests results for storing
            command: |
              mkdir test-results
              cp test-results.xml test-results/
            when: always
        - store_test_results:
            path: test-results
        - store_artifacts:
            path: test-results


workflows:
  say-hello-workflow:
    jobs:
      - build-and-test
